#!/bin/bash
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
echo -e "\e[32mloading...\e[0m"
clear
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "             MENU SHADOWSHOCKS            $NC"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "  ${ORANGE}1.${NC} \033[0;36m Create Account Shadowshocks WS/GRPC${NC}"
echo -e "  ${ORANGE}2.${NC} \033[0;36m Delete Account Shadowsocks WS/GRPC${NC}"
echo -e "  ${ORANGE}3.${NC} \033[0;36m Renew Shadowsocks Account${NC}"
echo -e "  ${ORANGE}4.${NC} \033[0;36m Check Shadowsocks login Account${NC}"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e ""
read -p "Select From Options [ 1 - 4 ] : " menu
case $menu in
1)
    addss
    ;;
2)
    delss
    ;;
3)
    renewss
    ;;
4)
    cekss
    ;;
*)
    menu
    ;;
esac
